INSERT INTO product (name, brand, type, image, price) VALUES
('Moisturizing Cream', 'CeraVe', 'Moisturizer', 'https://skincarerecs.blob.core.windows.net/images/cerave_moisturizing_cream.webp', 19.99),
('Anti-Aging Serum', 'Neutrogena', 'Serum', 'https://skincarerecs.blob.core.windows.net/images/neutrogena_serum.jpg', 29.99),
('Gentle Cleansing Lotion', 'La Roche-Posay', 'Cleanser', 'https://skincarerecs.blob.core.windows.net/images/la-roche-posay-toleriane-caring-wash.jpg', 15.49),
('Hydrating Toner', 'Thayers', 'Toner', 'https://skincarerecs.blob.core.windows.net/images/thayers-lait-tonique-hydratant.webp', 12.99),
('SPF 30 Sunscreen', 'EltaMD', 'Sunscreen', 'https://skincarerecs.blob.core.windows.net/images/elta_md_sunscreen.jpg', 24.95),
('Retinol Night Cream', 'RoC', 'Night Cream', 'https://skincarerecs.blob.core.windows.net/images/roc_retinol_night_cream.jpg', 22.50),
('Vitamin C Brightening Serum', 'TruSkin', 'Serum', 'https://skincarerecs.blob.core.windows.net/images/truskin_vitaminc_serum.jpg', 27.95),
('Glycolic Acid Exfoliating Cleanser', 'InstaNatural', 'Cleanser', 'https://skincarerecs.blob.core.windows.net/images/instanatural_cleanser.jpg', 18.75),
('Hyaluronic Acid Moisturizer', 'LOreal', 'Moisturizer', 'https://skincarerecs.blob.core.windows.net/images/loreal_cream.jpg', 21.99),
('Acne Spot Treatment', 'Mario Badescu', 'Treatment', 'https://skincarerecs.blob.core.windows.net/images/mariobadescu_lotion.webp', 12.00),
('Cleansing Oil', 'DHC', 'Cleanser', 'https://skincarerecs.blob.core.windows.net/images/dhc_cleanser.jpg', 28.50),
('AHA/BHA Peeling Solution', 'The Ordinary', 'Treatment', 'https://skincarerecs.blob.core.windows.net/images/theordinary_peeling_solution.webp', 7.99),
('Collagen Boosting Mask', 'Peter Thomas Roth', 'Mask', 'https://skincarerecs.blob.core.windows.net/images/firm_moisturizer.jpg', 34.99),
('Eye Cream', 'Olay', 'Eye Care', 'https://skincarerecs.blob.core.windows.net/images/olay_eye_cream.jpg', 16.79),
('Squalane Facial Oil', 'Biossance', 'Facial Oil', 'https://skincarerecs.blob.core.windows.net/images/biossance_oil.jpg', 29.00);