name: Build, Test and Deploy backend

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create Env File
        run: |
          touch env.properties
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo AZURE_ENDPOINT=${{ secrets.AZURE_ENDPOINT }} >> .env
          echo AZURE_KEY=${{ secrets.AZURE_KEY }} >> .env
          echo AZURE_ACCOUNT=${{ secrets.AZURE_ACCOUNT }} >> .env

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run and test with Maven
        run: mvn test

  docker_build_and_push:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t emsiish/skin-care-recs-backend:latest .

      - name: Push Docker image
        run: docker push emsiish/skin-care-recs-backend:latest